### PR TITLE
Small improvements 

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by flotho** [comment]
Hi @wpichler , it's been a long time and you're now the most advanced. 
So I propose you this small PR for correcting the category importation.

**Comment by flotho** [comment]
Hi @wpichler ,

any review possible of this PR ?

**Comment by wpichler** [comment]
Hi flotho,

thanks for the PR.

The inherits was not missing by mistake - it is missing by design.

The problem i did had here - is that i do use the magento.product.category for binding to product.category and for binding to product.public.category (if odoo ecommerce module is installed).

So i can't use a direct inherits here.

Two options here - create a separate model for the mapping of product.public.category - so we can use the inherits on both. Or do restore the inherits functionality (do create odoo category when magento category binding is created) in the binding model create function - or mapping function.

**Comment by flotho** [comment]
Hi @wpichler 

Thanks for the feedback.
I understand why the inherits has "disappeared".
Yet as I can see here https://github.com/wpichler/connector-magento/blob/10.0-callino-rebase/connector_magento/models/product_category/common.py#L42  the product.category binding. 
I can also see that this part https://github.com/wpichler/connector-magento/blob/10.0-callino-rebase/connector_magento_website_sale/models/product_category/common.py is binding with public category.
I'm not sure but I can't see where you choose which category is bound.
Regards

**Comment by flotho** [comment]
Hi @wpichler , is better from now ?

**Comment by wpichler** [comment]
Hi @flotho Looks great - i will merge it - and forward port it to the 12.0 branch (the magento2 connector does work great with odoo 12...)

**Pull request merged**
